language: ruby
# cache: bundler
install:
  - gem install bundler --version '1.14.6' --no-ri --no-rdoc
  - bundle install
script: bundle exec jekyll build
# sudo: enabled
rvm:
  - 2.5.1
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
