language: ruby
cache: bundler
install:
  - bundle install
script: bundle exec jekyll build
sudo: enabled
rvm:
  - 2.4.2
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
