author: Russell Chapman
description:
permalink: /posts/:categories/:title
title: Expert Enigma

github: [metadata]
github_username: chpmnrssll
github_repository: expert-enigma
github_branch: master

sass:
  style: compressed
  sass_dir: /assets/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
